"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from helpers import get_env, get_env_bool, get_env_csv, get_redis_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_env(
    'SECRET_KEY', default='django-insecure-82^imn$+)^pe+=9_q&d1y1t@_&c$#ju0y6y!)q*+i8-fn+1t7w')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_env_bool('DEBUG', default=False)

ALLOWED_HOSTS = get_env_csv('ALLOWED_HOSTS', default='localhost,127.0.0.1')

CSRF_TRUSTED_ORIGINS = get_env_csv(
    'CSRF_TRUSTED_ORIGINS', default="http://localhost:4200")

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'knox',
    'django_rq',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': get_env('DB_NAME', default='foretold_db'),
        'USER': get_env('DB_USER', default='foretold_user'),
        'PASSWORD': get_env('DB_PASSWORD', default='s5p2r&s4cr8t'),
        'HOST': get_env('DB_HOST', default='db'),
        'PORT': get_env('DB_PORT', default='5432'),
        'CONN_MAX_AGE': int(get_env('DB_CONN_MAX_AGE', default='60')),
    }
}

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': get_redis_url(),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient'
        },
        'TIMEOUT': int(get_env('CACHE_TIMEOUT', default='300')),
        'KEY_PREFIX': 'foretold',
    }
}

RQ_QUEUES = {
    'default': {
        'URL': get_redis_url(),
        'DEFAULT_TIMEOUT': int(get_env('RQ_DEFAULT_TIMEOUT', default='300')),
    }
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'knox.auth.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
}

CORS_ALLOWED_ORIGINS = get_env_csv('CORS_ALLOWED_ORIGINS', default='')

CORS_ALLOW_CREDENTIALS = get_env_bool('CORS_ALLOW_CREDENTIALS', default=False)

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = get_env('LANGUAGE_CODE', default='en-us')

TIME_ZONE = get_env('TIME_ZONE', default='Europe/Vienna')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / 'static'

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = get_env(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.console.EmailBackend',
)

DEFAULT_FROM_EMAIL = get_env(
    'DEFAULT_FROM_EMAIL', default='noreply@foretold.co')

SECURE_SSL_REDIRECT = get_env_bool('SECURE_SSL_REDIRECT', default=False)

SESSION_COOKIE_SECURE = get_env_bool('SESSION_COOKIE_SECURE', default=False)

CSRF_COOKIE_SECURE = get_env_bool('CSRF_COOKIE_SECURE', default=False)

LOG_LEVEL = get_env('LOG_LEVEL', default='INFO')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'console': {'format': '%(levelname)s %(asctime)s %(name)s: %(message)s'}
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'console'}
    },
    'root': {'handlers': ['console'], 'level': LOG_LEVEL},
}
